Update versioning.yml

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -5,18 +5,18 @@ on:
     branches:
       - main
     types:
-      - synchronize
+      - closed
 
 permissions:
   contents: write
 
 jobs:
   update-version:
-    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
+    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check out the repository
+      - name: Check out the dev branch
         uses: actions/checkout@v4
         with:
           ref: dev
@@ -40,3 +40,16 @@ jobs:
           git add .
           git commit -m "Incremented minor version to $(cat package.json | jq -r .version)" || echo "No changes to commit"
           git push origin dev || { echo "Error: Push to dev branch failed"; exit 1; }
+
+      - name: Check out the main branch
+        run: |
+          git fetch origin
+          git checkout main
+
+      - name: Merge dev into main
+        run: |
+          git merge dev --no-ff -m "Merging updated version from dev to main" || { echo "Error: Merge failed"; exit 1; }
+
+      - name: Push changes to main
+        run: |
+          git push origin main || { echo "Error: Push to main branch failed"; exit 1; }
